version: '2'
services:
  resync:
    image: resync:0.0.1
    network_mode: "bridge"
    ports:
      - "8050:8050"
    environment:
      - AppPort=8050
      - TaskQueueSize=10
      - ActorSize=2
      - Mode=release
      - DefaultAdminName=resync
      - DefaultAdminPasswd=resynz
    command: /bin/resync
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"